version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13
    container_name: rabbitmq
    volumes:
        - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
        - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5552:5552"
      - "15672:15672"
      - "5672:5672"
    environment:
      #- RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost
      #- RABBITMQ_DEFAULT_USER=marcus
      #- RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFINITIONS_FILE=/etc/rabbitmq/definitions.json
      - RABBITMQ_DEFAULT_VHOST=/